# Generated by Django 4.2 on 2023-04-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('cache_duration', models.IntegerField(null=True)),
                ('scope', models.CharField(max_length=255, null=True)),
                ('handler', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField(null=True)),
                ('alliance_id', models.BigIntegerField(null=True)),
                ('birthday', models.CharField(max_length=50, null=True)),
                ('bloodline_id', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('faction_id', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('race_id', models.IntegerField(null=True)),
                ('security_status', models.FloatField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corporation_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('alliance_id', models.BigIntegerField(null=True)),
                ('ceo_id', models.BigIntegerField()),
                ('creator_id', models.BigIntegerField()),
                ('date_founded', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('faction_id', models.IntegerField(null=True)),
                ('home_station_id', models.BigIntegerField(null=True)),
                ('member_count', models.IntegerField(null=True)),
                ('shares', models.BigIntegerField(null=True)),
                ('tax_rate', models.FloatField()),
                ('ticker', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=255, null=True)),
                ('war_eligible', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWallet',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='esi_app.character')),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CorporationWalletTransaction',
            fields=[
                ('division_id', models.IntegerField()),
                ('client_id', models.BigIntegerField()),
                ('date', models.CharField(max_length=50)),
                ('is_buy', models.BooleanField()),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField()),
                ('unit_price', models.FloatField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='CorporationWalletJournal',
            fields=[
                ('division_id', models.IntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('context_id', models.BigIntegerField(null=True)),
                ('context_id_type', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('first_party_id', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('ref_type', models.CharField(max_length=100)),
                ('second_party_id', models.BigIntegerField()),
                ('tax', models.FloatField(null=True)),
                ('tax_receiver_id', models.FloatField(null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='CorporationWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField()),
                ('balance', models.FloatField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='esi_app.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='CorporationDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
                ('division', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWalletTransaction',
            fields=[
                ('client_id', models.BigIntegerField()),
                ('date', models.CharField(max_length=50)),
                ('is_buy', models.BooleanField()),
                ('is_personal', models.BooleanField()),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField()),
                ('unit_price', models.FloatField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWalletJournal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('context_id', models.BigIntegerField(null=True)),
                ('context_id_type', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('first_party_id', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('ref_type', models.CharField(max_length=100)),
                ('second_party_id', models.BigIntegerField()),
                ('tax', models.FloatField(null=True)),
                ('tax_receiver_id', models.FloatField(null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_execution', models.BigIntegerField(null=True)),
                ('last_result', models.CharField(max_length=1500, null=True)),
                ('api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esi_app.api')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='esi_app.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1500)),
                ('refresh_token', models.CharField(max_length=50)),
                ('issued_at', models.BigIntegerField(null=True)),
                ('expire_time', models.BigIntegerField(null=True)),
                ('scopes', models.CharField(max_length=3000, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='esi_app.character')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi_app.apigroup'),
        ),
    ]
